### ISSUE TITLE
无法发送邮件

### ISSUE THREAD

**Issue by chengziorange** [v2board/v2board#158]
一开始是数据库的v2_mail_log表里有 `Cannot send message without a sender address` ，后来修改.env和config/Mail.php之后，数据库里failed_jobs表里又出现条目：  
payloud
```
{"timeout":null,"id":"MVH93l5rkQeaM3mBAr2jiLGqyel4v4KW","data":{"command":"O:21:\"App\\Jobs\\SendEmailJob\":9:{s:9:\"\u0000*\u0000params\";a:4:{s:5:\"email\";s:21:\"test@163.com\";s:7:\"subject\";s:1:\"5\";s:13:\"template_name\";s:6:\"notify\";s:14:\"template_value\";a:3:{s:4:\"name\";s:15:\"XXXXX\";s:3:\"url\";s:25:\"https:\/\/test.com\";s:7:\"content\";s:1:\"5\";}}s:6:\"\u0000*\u0000job\";N;s:10:\"connection\";N;s:5:\"queue\";s:10:\"send_email\";s:15:\"chainConnection\";N;s:10:\"chainQueue\";N;s:5:\"delay\";N;s:10:\"middleware\";a:0:{}s:7:\"chained\";a:0:{}}","commandName":"App\\Jobs\\SendEmailJob"},"displayName":"App\\Jobs\\SendEmailJob","timeoutAt":null,"job":"Illuminate\\Queue\\CallQueuedHandler@call","maxTries":null,"delay":null,"attempts":1}
```
exception
```
Illuminate\Queue\MaxAttemptsExceededException: App\Jobs\SendEmailJob has been attempted too many times or run too long. The job may have previously timed out. in /home/wwwroot/test.com/vendor/laravel/framework/src/Illuminate/Queue/Worker.php:632
Stack trace:
#0 /home/wwwroot/test.com/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(446): Illuminate\Queue\Worker->maxAttemptsExceededException()
#1 /home/wwwroot/test.com/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(358): Illuminate\Queue\Worker->markJobAsFailedIfAlreadyExceedsMaxAttempts()
#2 /home/wwwroot/test.com/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(314): Illuminate\Queue\Worker->process()
#3 /home/wwwroot/test.com/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(134): Illuminate\Queue\Worker->runJob()
#4 /home/wwwroot/test.com/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(112): Illuminate\Queue\Worker->daemon()
#5 /home/wwwroot/test.com/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(96): Illuminate\Queue\Console\WorkCommand->runWorker()
#6 [internal function]: Illuminate\Queue\Console\WorkCommand->handle()
#7 /home/wwwroot/test.com/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(32): call_user_func_array()
#8 /home/wwwroot/test.com/vendor/laravel/framework/src/Illuminate/Container/Util.php(36): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#9 /home/wwwroot/test.com/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(90): Illuminate\Container\Util::unwrapIfClosure()
#10 /home/wwwroot/test.com/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(34): Illuminate\Container\BoundMethod::callBoundMethod()
#11 /home/wwwroot/test.com/vendor/laravel/framework/src/Illuminate/Container/Container.php(590): Illuminate\Container\BoundMethod::call()
#12 /home/wwwroot/test.com/vendor/laravel/framework/src/Illuminate/Console/Command.php(134): Illuminate\Container\Container->call()
#13 /home/wwwroot/test.com/vendor/symfony/console/Command/Command.php(255): Illuminate\Console\Command->execute()
#14 /home/wwwroot/test.com/vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\Component\Console\Command\Command->run()
#15 /home/wwwroot/test.com/vendor/symfony/console/Application.php(1001): Illuminate\Console\Command->run()
#16 /home/wwwroot/test.com/vendor/symfony/console/Application.php(271): Symfony\Component\Console\Application->doRunCommand()
#17 /home/wwwroot/test.com/vendor/symfony/console/Application.php(147): Symfony\Component\Console\Application->doRun()
#18 /home/wwwroot/test.com/vendor/laravel/framework/src/Illuminate/Console/Application.php(93): Symfony\Component\Console\Application->run()
#19 /home/wwwroot/test.com/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(131): Illuminate\Console\Application->run()
#20 /home/wwwroot/test.com/artisan(37): Illuminate\Foundation\Console\Kernel->handle()
#21 {main}
```

**Comment by wbmvincent** [comment]
我也是同样的问题，折腾一天了，请问解决了吗？

**Comment by chengziorange** [comment]
> 我也是同样的问题，折腾一天了，请问解决了吗？

没有，我直接放弃了（

**Comment by wbmvincent** [comment]
我换了微软的邮箱之后可以发了，看来不是配置的问题
