### ISSUE TITLE
关于文档中部分表述的一点疑问

### ISSUE THREAD

**Issue by starP-W** [v2board/v2board#22]
文档[添加站点](https://docs.v2board.com/bu-shu/kai-shi#5-tian-jia-zhan-dian)中提到
```
Domain：填入你指向服务器的域名
Database：MySQL
PHP version：PHP-73
```
此处是否需要创建一个与.env 文件同名同用户的数据库？
此外文档中还提到
>完成创建后访问站点目录删除目录下的所有文件

具体是删除什么呢？需要在网站目录底下rm -rf * 吗？

**Comment by tokumeikoi** [comment]
aapanel创建完站点后有一些html文件和apache的伪静态文件需要删除，否则git到当前目录会失败

**Comment by starP-W** [comment]
> aapanel创建完站点后有一些html文件和apache的伪静态文件需要删除，否则git到当前目录会失败

按照教程，123步均按照文档进行，完成后先执行第5步中的创建站点及数据库并删除index.html、404.html、.user.ini及.htaccess(即站点创建时的所有文件)，随后完整按照第4步执行操作，最后完成第5步中未进行的操作。预期按照上述步骤应该可以完成站点的搭建，然而访问时依旧报500错误，查询日志如下

```
[2020-01-30 07:59:35] local.ERROR: No application encryption key has been specified. {"exception":"[object] (RuntimeException(code: 0): No application encryption key has been specified. at /www/wwwroot/vl.starp.cf/vendor/laravel/framework/src/Illuminate/Encryption/EncryptionServiceProvider.php:44)
[stacktrace]
#0 /www/wwwroot/vl.starp.cf/vendor/laravel/framework/src/Illuminate/Support/helpers.php(422): Illuminate\\Encryption\\EncryptionServiceProvider->Illuminate\\Encryption\\{closure}('')
#1 /www/wwwroot/vl.starp.cf/vendor/laravel/framework/src/Illuminate/Encryption/EncryptionServiceProvider.php(48): tap('', Object(Closure))
#2 /www/wwwroot/vl.starp.cf/vendor/laravel/framework/src/Illuminate/Encryption/EncryptionServiceProvider.php(24): Illuminate\\Encryption\\EncryptionServiceProvider->key(Array)
#3 /www/wwwroot/vl.starp.cf/vendor/laravel/framework/src/Illuminate/Container/Container.php(799): Illuminate\\Encryption\\EncryptionServiceProvider->Illuminate\\Encryption\\{closure}(Object(Illuminate\\Foundation\\Application), Array)
#4 /www/wwwroot/vl.starp.cf/vendor/laravel/framework/src/Illuminate/Container/Container.php(681): Illuminate\\Container\\Container->build(Object(Closure))
#5 /www/wwwroot/vl.starp.cf/vendor/laravel/framework/src/Illuminate/Container/Container.php(629): Illuminate\\Container\\Container->resolve('encrypter', Array)
#6 /www/wwwroot/vl.starp.cf/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(776): Illuminate\\Container\\Container->make('encrypter', Array)
#7 /www/wwwroot/vl.starp.cf/vendor/laravel/framework/src/Illuminate/Container/Container.php(945): Illuminate\\Foundation\\Application->make('encrypter')
#8 /www/wwwroot/vl.starp.cf/vendor/laravel/framework/src/Illuminate/Container/Container.php(873): Illuminate\\Container\\Container->resolveClass(Object(ReflectionParameter))
#9 /www/wwwroot/vl.starp.cf/vendor/laravel/framework/src/Illuminate/Container/Container.php(834): Illuminate\\Container\\Container->resolveDependencies(Array)
#10 /www/wwwroot/vl.starp.cf/vendor/laravel/framework/src/Illuminate/Container/Container.php(681): Illuminate\\Container\\Container->build('App\\\\Http\\\\Middle...')
#11 /www/wwwroot/vl.starp.cf/vendor/laravel/framework/src/Illuminate/Container/Container.php(629): Illuminate\\Container\\Container->resolve('App\\\\Http\\\\Middle...', Array)
#12 /www/wwwroot/vl.starp.cf/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(776): Illuminate\\Container\\Container->make('App\\\\Http\\\\Middle...', Array)
#13 /www/wwwroot/vl.starp.cf/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(160): Illuminate\\Foundation\\Application->make('App\\\\Http\\\\Middle...')
#14 /www/wwwroot/vl.starp.cf/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#15 /www/wwwroot/vl.starp.cf/vendor/laravel/framework/src/Illuminate/Routing/Router.php(683): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#16 /www/wwwroot/vl.starp.cf/vendor/laravel/framework/src/Illuminate/Routing/Router.php(658): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#17 /www/wwwroot/vl.starp.cf/vendor/laravel/framework/src/Illuminate/Routing/Router.php(624): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#18 /www/wwwroot/vl.starp.cf/vendor/laravel/framework/src/Illuminate/Routing/Router.php(613): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#19 /www/wwwroot/vl.starp.cf/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(170): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#20 /www/wwwroot/vl.starp.cf/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#21 /www/wwwroot/vl.starp.cf/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#22 /www/wwwroot/vl.starp.cf/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#23 /www/wwwroot/vl.starp.cf/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#24 /www/wwwroot/vl.starp.cf/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#25 /www/wwwroot/vl.starp.cf/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#26 /www/wwwroot/vl.starp.cf/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#27 /www/wwwroot/vl.starp.cf/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(63): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#28 /www/wwwroot/vl.starp.cf/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#29 /www/wwwroot/vl.starp.cf/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#30 /www/wwwroot/vl.starp.cf/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Fideloper\\Proxy\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#31 /www/wwwroot/vl.starp.cf/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#32 /www/wwwroot/vl.starp.cf/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(145): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#33 /www/wwwroot/vl.starp.cf/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(110): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#34 /www/wwwroot/vl.starp.cf/public/index.php(55): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#35 {main}
"} 
[2020-01-30 07:59:35] local.ERROR: No application encryption key has been specified. {"exception":"[object] (RuntimeException(code: 0): No application encryption key has been specified. at /www/wwwroot/vl.starp.cf/vendor/laravel/framework/src/Illuminate/Encryption/EncryptionServiceProvider.php:44)
[stacktrace]
#0 /www/wwwroot/vl.starp.cf/vendor/laravel/framework/src/Illuminate/Support/helpers.php(422): Illuminate\\Encryption\\EncryptionServiceProvider->Illuminate\\Encryption\\{closure}('')
#1 /www/wwwroot/vl.starp.cf/vendor/laravel/framework/src/Illuminate/Encryption/EncryptionServiceProvider.php(48): tap('', Object(Closure))
#2 /www/wwwroot/vl.starp.cf/vendor/laravel/framework/src/Illuminate/Encryption/EncryptionServiceProvider.php(24): Illuminate\\Encryption\\EncryptionServiceProvider->key(Array)
#3 /www/wwwroot/vl.starp.cf/vendor/laravel/framework/src/Illuminate/Container/Container.php(799): Illuminate\\Encryption\\EncryptionServiceProvider->Illuminate\\Encryption\\{closure}(Object(Illuminate\\Foundation\\Application), Array)
#4 /www/wwwroot/vl.starp.cf/vendor/laravel/framework/src/Illuminate/Container/Container.php(681): Illuminate\\Container\\Container->build(Object(Closure))
#5 /www/wwwroot/vl.starp.cf/vendor/laravel/framework/src/Illuminate/Container/Container.php(629): Illuminate\\Container\\Container->resolve('encrypter', Array)
#6 /www/wwwroot/vl.starp.cf/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(776): Illuminate\\Container\\Container->make('encrypter', Array)
#7 /www/wwwroot/vl.starp.cf/vendor/laravel/framework/src/Illuminate/Container/Container.php(945): Illuminate\\Foundation\\Application->make('encrypter')
#8 /www/wwwroot/vl.starp.cf/vendor/laravel/framework/src/Illuminate/Container/Container.php(873): Illuminate\\Container\\Container->resolveClass(Object(ReflectionParameter))
#9 /www/wwwroot/vl.starp.cf/vendor/laravel/framework/src/Illuminate/Container/Container.php(834): Illuminate\\Container\\Container->resolveDependencies(Array)
#10 /www/wwwroot/vl.starp.cf/vendor/laravel/framework/src/Illuminate/Container/Container.php(681): Illuminate\\Container\\Container->build('App\\\\Http\\\\Middle...')
#11 /www/wwwroot/vl.starp.cf/vendor/laravel/framework/src/Illuminate/Container/Container.php(629): Illuminate\\Container\\Container->resolve('App\\\\Http\\\\Middle...', Array)
#12 /www/wwwroot/vl.starp.cf/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(776): Illuminate\\Container\\Container->make('App\\\\Http\\\\Middle...', Array)
#13 /www/wwwroot/vl.starp.cf/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(209): Illuminate\\Foundation\\Application->make('App\\\\Http\\\\Middle...')
#14 /www/wwwroot/vl.starp.cf/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(183): Illuminate\\Foundation\\Http\\Kernel->terminateMiddleware(Object(Illuminate\\Http\\Request), Object(Illuminate\\Http\\Response))
#15 /www/wwwroot/vl.starp.cf/public/index.php(60): Illuminate\\Foundation\\Http\\Kernel->terminate(Object(Illuminate\\Http\\Request), Object(Illuminate\\Http\\Response))
#16 {main}
"} 

```

**Comment by tokumeikoi** [comment]
这个问题之前复现过，还没有找到原因，你可以执行sh init.sh然后重新给权限就可以正常访问了

**Comment by starP-W** [comment]
尝试了一下，又开始报类似于[#9](https://github.com/v2board/v2board/issues/9)的错误了，暂时静待更多更新，感谢开发者的付出
