### ISSUE TITLE
500 server error

### ISSUE THREAD

**Issue by chenzhikang** [v2board/v2board#415]
I don't see a similar error in issue.

error log:

2021/04/02 17:59:49 [error] 26369#0: *1898 FastCGI sent in stderr: "PHP message: PHP Fatal error: 
 Uncaught ErrorException: file_put_contents(/www/wwwroot/panel.daishuvpn.top/storage/framework/views/5b693162c3cc60ddd2366a32cd5e197826011354.php):
  failed to open stream: Permission denied in /www/wwwroot/panel.daishuvpn.top/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php:133
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError()
#1 /www/wwwroot/panel.daishuvpn.top/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php(133): file_put_contents()
#2 /www/wwwroot/panel.daishuvpn.top/vendor/laravel/framework/src/Illuminate/View/Compilers/BladeCompiler.php(129): Illuminate\Filesystem\Filesystem->put()
#3 /www/wwwroot/panel.daishuvpn.top/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(51): Illuminate\View\Compilers\BladeCompiler->compile()
#4 /www/wwwroot/panel.daishuvpn.top/vendor/facade/ignition/src/Views/Engines/CompilerEngine.php(36): Illuminate\View\Engines\CompilerEngine...PHP message: PHP Fatal error:  Uncaught ErrorException: file_put_contents(/www/wwwroot/panel.daishuvpn.top/storage/framework/views/5b693162c3cc60ddd2366a32cd5e197826011354.php): failed to open stream: Permission denied in /www/wwwroot/panel.daishuvpn.top/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php:133
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError()
#1 /www/wwwroot/panel.daishuvpn.top/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php(133): file_put_contents()
#2 /www/wwwroot/panel.daishuvpn.top/vendor/laravel/framework/src/Illuminate/View/Compilers/BladeCompiler.php(129): Illuminate\Filesystem\Filesystem->put()
#3 /www/wwwroot/panel.daishuvpn.top/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(51): Illuminate\View\Compilers\BladeCompiler->compile()
#4 /www/wwwroot/panel.daishuvpn.top/vendor/facade/ignition/src/Views/Engines/CompilerEngine

**Comment by chenzhikang** [comment]
I've added 755 recursive permissions
