### ISSUE TITLE
[BUG]单服务器安装两个或以上面板，队列服务有概率报错

### ISSUE THREAD

**Issue by syouko** [v2board/v2board#629]
The V2Board version number you are using
当前使用的V2Board版本号
--------
1.7.2

Briefly describe the problem you are experiencing
简单描述你遇到的问题
--------
在同一台服务器中，安装两个 V2Board 面板。
安装在不同目录中，使用不同的数据库 (废话= =)。
队列服务与定时任务均分别运行。

当产生需要队列服务处理的任务时，有概率会被另一个站点的队列服务去处理。从而导致报错。

例如一台服务器中安装了面板 A与B。
当A进来一条需要开通的订单时，可能B的队列服务会抢先于A的队列服务进行处理。
但由于订单不是面板A的，所以会报错
 `Failed: App\Jobs\OrderHandleJob`

之后的定时任务 check order 时。
如果是面板B的check任务，不会触发该订单的开通流程。
面板A的check任务执行时会再次触发队列服务，再次随机由其中一个队列执行。
如果碰巧被队列A执行到了，那么成功。运气不好的话就一直开通不了了。
(感觉先启动的队列更容易抢到任务)

注意到两个面板的 “指标：队列监控” 也是数据共享的。

Screenshot of the reported error(Please do desensitization)
报告错误的截图（请做脱敏处理）
--------
处理非本面板数据后，该站数据库 failed_jobs 中的报错：
**exception**
```
Illuminate\Database\Eloquent\ModelNotFoundException: No query results for model [App\Models\Order]. in /www/wwwroot/sitedir/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php:527
Stack trace:
#0 /www/wwwroot/sitedir/vendor/laravel/framework/src/Illuminate/Queue/SerializesAndRestoresModelIdentifiers.php(102): Illuminate\Database\Eloquent\Builder->firstOrFail()
#1 /www/wwwroot/sitedir/vendor/laravel/framework/src/Illuminate/Queue/SerializesAndRestoresModelIdentifiers.php(57): App\Jobs\OrderHandleJob->restoreModel()
#2 /www/wwwroot/sitedir/vendor/laravel/framework/src/Illuminate/Queue/SerializesModels.php(122): App\Jobs\OrderHandleJob->getRestoredPropertyValue()
#3 [internal function]: App\Jobs\OrderHandleJob->__unserialize()
#4 /www/wwwroot/sitedir/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(97): unserialize()
#5 /www/wwwroot/sitedir/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(60): Illuminate\Queue\CallQueuedHandler->getCommand()
#6 /www/wwwroot/sitedir/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(98): Illuminate\Queue\CallQueuedHandler->call()
#7 /www/wwwroot/sitedir/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(428): Illuminate\Queue\Jobs\Job->fire()
#8 /www/wwwroot/sitedir/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(378): Illuminate\Queue\Worker->process()
#9 /www/wwwroot/sitedir/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(172): Illuminate\Queue\Worker->runJob()
#10 /www/wwwroot/sitedir/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(117): Illuminate\Queue\Worker->daemon()
#11 /www/wwwroot/sitedir/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(101): Illuminate\Queue\Console\WorkCommand->runWorker()
#12 /www/wwwroot/sitedir/vendor/laravel/horizon/src/Console/WorkCommand.php(51): Illuminate\Queue\Console\WorkCommand->handle()
#13 /www/wwwroot/sitedir/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Laravel\Horizon\Console\WorkCommand->handle()
#14 /www/wwwroot/sitedir/vendor/laravel/framework/src/Illuminate/Container/Util.php(40): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#15 /www/wwwroot/sitedir/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure()
#16 /www/wwwroot/sitedir/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\Container\BoundMethod::callBoundMethod()
#17 /www/wwwroot/sitedir/vendor/laravel/framework/src/Illuminate/Container/Container.php(653): Illuminate\Container\BoundMethod::call()
#18 /www/wwwroot/sitedir/vendor/laravel/framework/src/Illuminate/Console/Command.php(136): Illuminate\Container\Container->call()
#19 /www/wwwroot/sitedir/vendor/symfony/console/Command/Command.php(298): Illuminate\Console\Command->execute()
#20 /www/wwwroot/sitedir/vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\Component\Console\Command\Command->run()
#21 /www/wwwroot/sitedir/vendor/symfony/console/Application.php(1040): Illuminate\Console\Command->run()
#22 /www/wwwroot/sitedir/vendor/symfony/console/Application.php(301): Symfony\Component\Console\Application->doRunCommand()
#23 /www/wwwroot/sitedir/vendor/symfony/console/Application.php(171): Symfony\Component\Console\Application->doRun()
#24 /www/wwwroot/sitedir/vendor/laravel/framework/src/Illuminate/Console/Application.php(94): Symfony\Component\Console\Application->run()
#25 /www/wwwroot/sitedir/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(129): Illuminate\Console\Application->run()
#26 /www/wwwroot/sitedir/artisan(37): Illuminate\Foundation\Console\Kernel->handle()
#27 {main}
```

**payload**
```
{"uuid":"be5e371a-f338-4585-92f2-d47c9cadc530","displayName":"App\\Jobs\\OrderHandleJob","job":"Illuminate\\Queue\\CallQueuedHandler@call","maxTries":null,"maxExceptions":null,"failOnTimeout":false,"backoff":null,"timeout":null,"retryUntil":null,"data":{"commandName":"App\\Jobs\\OrderHandleJob","command":"O:23:\"App\\Jobs\\OrderHandleJob\":11:{s:8:\"\u0000*\u0000order\";O:45:\"Illuminate\\Contracts\\Database\\ModelIdentifier\":4:{s:5:\"class\";s:16:\"App\\Models\\Order\";s:2:\"id\";i:2714;s:9:\"relations\";a:0:{}s:10:\"connection\";s:5:\"mysql\";}s:3:\"job\";N;s:10:\"connection\";N;s:5:\"queue\";s:12:\"order_handle\";s:15:\"chainConnection\";N;s:10:\"chainQueue\";N;s:19:\"chainCatchCallbacks\";N;s:5:\"delay\";N;s:11:\"afterCommit\";N;s:10:\"middleware\";a:0:{}s:7:\"chained\";a:0:{}}"},"id":"be5e371a-f338-4585-92f2-d47c9cadc530","attempts":0,"type":"job","tags":["App\\Models\\Order:2714"],"pushedAt":"1673115314.5716"}
```

The latest log files in the storage/logs directory report from #1 (Please do desensitization)
storage/logs 目录下最新的日志文件从 #1 开始报告（请做脱敏处理）
--------
无logs

**Comment by tokumeikoi** [comment]
有没有可能redis要做隔离

**Comment by syouko** [comment]
> 

0.0 抱歉，没有这方面只是... 我去查查看，谢谢
