### ISSUE TITLE
[BUG]无法节点编辑排序，保存后又回到原来的位置

### ISSUE THREAD

**Issue by lajichang0** [v2board/v2board#726]
🙇‍♂️🙇‍♂️🙇‍♂️注意：XrayR等非V2Board问题请前往项目方提问
🙇‍♂️🙇‍♂️🙇‍♂️Note: XrayR and other non-V2Board issues please go to the project side to ask questions

The V2Board version number you are using
当前使用的V2Board版本号
--------
1.7.3

Briefly describe the problem you are experiencing
简单描述你遇到的问题
--------
无法节点编辑排序，节点保存后又回到原来的位置

Screenshot of the reported error(Please do desensitization)
报告错误的截图（请做脱敏处理）
--------
12544  "} 
  12545: [2023-03-13 00:01:24] local.ERROR: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '194-vmess-1678636800' for key 'server_id_server_type_record_at' (SQL: insert into `v2_stat_server` (`server_id`, `server_type`, `u`, `d`, `record_type`, `record_at`, `updated_at`, `created_at`) values (194, vmess, 86, 127, d, 1678636800, 1678636884, 1678636884)) {"exception":"[object] (Illuminate\\Database\\QueryException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '194-vmess-1678636800' for key 'server_id_server_type_record_at' (SQL: insert into `v2_stat_server` (`server_id`, `server_type`, `u`, `d`, `record_type`, `record_at`, `updated_at`, `created_at`) values (194, vmess, 86, 127, d, 1678636800, 1678636884, 1678636884)) at /www/wwwroot/xxx.com/vendor/laravel/framework/src/Illuminate/Database/Connection.php:712)
  12546  [stacktrace]

  12656  "} 
  12657: [2023-03-13 00:01:27] local.ERROR: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '236-vmess-1678636800' for key 'server_id_server_type_record_at' (SQL: insert into `v2_stat_server` (`server_id`, `server_type`, `u`, `d`, `record_type`, `record_at`, `updated_at`, `created_at`) values (236, vmess, 86, 127, d, 1678636800, 1678636887, 1678636887)) {"exception":"[object] (Illuminate\\Database\\QueryException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '236-vmess-1678636800' for key 'server_id_server_type_record_at' (SQL: insert into `v2_stat_server` (`server_id`, `server_type`, `u`, `d`, `record_type`, `record_at`, `updated_at`, `created_at`) values (236, vmess, 86, 127, d, 1678636800, 1678636887, 1678636887)) at /www/wwwroot/xxx.com/vendor/laravel/framework/src/Illuminate/Database/Connection.php:712)
  12658  [stacktrace]

  12768  "} 
  12769: [2023-03-13 00:01:27] local.ERROR: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '236-vmess-1678636800' for key 'server_id_server_type_record_at' (SQL: insert into `v2_stat_server` (`server_id`, `server_type`, `u`, `d`, `record_type`, `record_at`, `updated_at`, `created_at`) values (236, vmess, 86, 127, d, 1678636800, 1678636887, 1678636887)) {"exception":"[object] (Illuminate\\Database\\QueryException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '236-vmess-1678636800' for key 'server_id_server_type_record_at' (SQL: insert into `v2_stat_server` (`server_id`, `server_type`, `u`, `d`, `record_type`, `record_at`, `updated_at`, `created_at`) values (236, vmess, 86, 127, d, 1678636800, 1678636887, 1678636887)) at /www/wwwroot/xxx.com/vendor/laravel/framework/src/Illuminate/Database/Connection.php:712)
  12770  [stacktrace]

  12880  "} 
  12881: [2023-03-13 00:01:28] local.ERROR: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '325-vmess-1678636800' for key 'server_id_server_type_record_at' (SQL: insert into `v2_stat_server` (`server_id`, `server_type`, `u`, `d`, `record_type`, `record_at`, `updated_at`, `created_at`) values (325, vmess, 86, 127, d, 1678636800, 1678636888, 1678636888)) {"exception":"[object] (Illuminate\\Database\\QueryException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '325-vmess-1678636800' for key 'server_id_server_type_record_at' (SQL: insert into `v2_stat_server` (`server_id`, `server_type`, `u`, `d`, `record_type`, `record_at`, `updated_at`, `created_at`) values (325, vmess, 86, 127, d, 1678636800, 1678636888, 1678636888)) at /www/wwwroot/xxx.com/vendor/laravel/framework/src/Illuminate/Database/Connection.php:712)
  12882  [stacktrace]

  12992  "} 
  12993: [2023-03-13 00:44:03] local.ERROR: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '280-vmess-1678636800' for key 'server_id_server_type_record_at' (SQL: insert into `v2_stat_server` (`server_id`, `server_type`, `u`, `d`, `record_type`, `record_at`, `updated_at`, `created_at`) values (280, vmess, 88, 778, d, 1678636800, 1678639443, 1678639443)) {"exception":"[object] (Illuminate\\Database\\QueryException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '280-vmess-1678636800' for key 'server_id_server_type_record_at' (SQL: insert into `v2_stat_server` (`server_id`, `server_type`, `u`, `d`, `record_type`, `record_at`, `updated_at`, `created_at`) values (280, vmess, 88, 778, d, 1678636800, 1678639443, 1678639443)) at /www/wwwroot/xxx.com/vendor/laravel/framework/src/Illuminate/Database/Connection.php:712)
  12994  [stacktrace]

Screenshot of the reported error(Please do desensitization)
报告错误的截图（请做脱敏处理）
--------
12544  "} 
  12545: [2023-03-13 00:01:24] local.ERROR: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '194-vmess-1678636800' for key 'server_id_server_type_record_at' (SQL: insert into `v2_stat_server` (`server_id`, `server_type`, `u`, `d`, `record_type`, `record_at`, `updated_at`, `created_at`) values (194, vmess, 86, 127, d, 1678636800, 1678636884, 1678636884)) {"exception":"[object] (Illuminate\\Database\\QueryException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '194-vmess-1678636800' for key 'server_id_server_type_record_at' (SQL: insert into `v2_stat_server` (`server_id`, `server_type`, `u`, `d`, `record_type`, `record_at`, `updated_at`, `created_at`) values (194, vmess, 86, 127, d, 1678636800, 1678636884, 1678636884)) at /www/wwwroot/xxx.com/vendor/laravel/framework/src/Illuminate/Database/Connection.php:712)
  12546  [stacktrace]

  12656  "} 
  12657: [2023-03-13 00:01:27] local.ERROR: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '236-vmess-1678636800' for key 'server_id_server_type_record_at' (SQL: insert into `v2_stat_server` (`server_id`, `server_type`, `u`, `d`, `record_type`, `record_at`, `updated_at`, `created_at`) values (236, vmess, 86, 127, d, 1678636800, 1678636887, 1678636887)) {"exception":"[object] (Illuminate\\Database\\QueryException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '236-vmess-1678636800' for key 'server_id_server_type_record_at' (SQL: insert into `v2_stat_server` (`server_id`, `server_type`, `u`, `d`, `record_type`, `record_at`, `updated_at`, `created_at`) values (236, vmess, 86, 127, d, 1678636800, 1678636887, 1678636887)) at /www/wwwroot/xxx.com/vendor/laravel/framework/src/Illuminate/Database/Connection.php:712)
  12658  [stacktrace]

  12768  "} 
  12769: [2023-03-13 00:01:27] local.ERROR: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '236-vmess-1678636800' for key 'server_id_server_type_record_at' (SQL: insert into `v2_stat_server` (`server_id`, `server_type`, `u`, `d`, `record_type`, `record_at`, `updated_at`, `created_at`) values (236, vmess, 86, 127, d, 1678636800, 1678636887, 1678636887)) {"exception":"[object] (Illuminate\\Database\\QueryException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '236-vmess-1678636800' for key 'server_id_server_type_record_at' (SQL: insert into `v2_stat_server` (`server_id`, `server_type`, `u`, `d`, `record_type`, `record_at`, `updated_at`, `created_at`) values (236, vmess, 86, 127, d, 1678636800, 1678636887, 1678636887)) at /www/wwwroot/xxx.com/vendor/laravel/framework/src/Illuminate/Database/Connection.php:712)
  12770  [stacktrace]

  12880  "} 
  12881: [2023-03-13 00:01:28] local.ERROR: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '325-vmess-1678636800' for key 'server_id_server_type_record_at' (SQL: insert into `v2_stat_server` (`server_id`, `server_type`, `u`, `d`, `record_type`, `record_at`, `updated_at`, `created_at`) values (325, vmess, 86, 127, d, 1678636800, 1678636888, 1678636888)) {"exception":"[object] (Illuminate\\Database\\QueryException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '325-vmess-1678636800' for key 'server_id_server_type_record_at' (SQL: insert into `v2_stat_server` (`server_id`, `server_type`, `u`, `d`, `record_type`, `record_at`, `updated_at`, `created_at`) values (325, vmess, 86, 127, d, 1678636800, 1678636888, 1678636888)) at /www/wwwroot/xxx.com/vendor/laravel/framework/src/Illuminate/Database/Connection.php:712)
  12882  [stacktrace]

  12992  "} 
  12993: [2023-03-13 00:44:03] local.ERROR: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '280-vmess-1678636800' for key 'server_id_server_type_record_at' (SQL: insert into `v2_stat_server` (`server_id`, `server_type`, `u`, `d`, `record_type`, `record_at`, `updated_at`, `created_at`) values (280, vmess, 88, 778, d, 1678636800, 1678639443, 1678639443)) {"exception":"[object] (Illuminate\\Database\\QueryException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '280-vmess-1678636800' for key 'server_id_server_type_record_at' (SQL: insert into `v2_stat_server` (`server_id`, `server_type`, `u`, `d`, `record_type`, `record_at`, `updated_at`, `created_at`) values (280, vmess, 88, 778, d, 1678636800, 1678639443, 1678639443)) at /www/wwwroot/xxx.com/vendor/laravel/framework/src/Illuminate/Database/Connection.php:712)
  12994  [stacktrace]

The latest log files in the storage/logs directory report from #1 (Please do desensitization)
storage/logs 目录下最新的日志文件从 #1 开始报告（请做脱敏处理）
--------
[2023-03-13 00:00:00] local.ERROR: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '117-vmess-1678636800' for key 'server_id_server_type_record_at' (SQL: insert into `v2_stat_server` (`server_id`, `server_type`, `u`, `d`, `record_type`, `record_at`, `updated_at`, `created_at`) values (117, vmess, 46603, 162364019, d, 1678636800, 1678636800, 1678636800)) {"exception":"[object] (Illuminate\\Database\\QueryException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '117-vmess-1678636800' for key 'server_id_server_type_record_at' (SQL: insert into `v2_stat_server` (`server_id`, `server_type`, `u`, `d`, `record_type`, `record_at`, `updated_at`, `created_at`) values (117, vmess, 46603, 162364019, d, 1678636800, 1678636800, 1678636800)) at /www/wwwroot/xxx.com/vendor/laravel/framework/src/Illuminate/Database/Connection.php:712)
[stacktrace]
#0 /www/wwwroot/xxx.com/vendor/laravel/framework/src/Illuminate/Database/Connection.php(672): Illuminate\\Database\\Connection->runQueryCallback()
#1 /www/wwwroot/xxx.com/vendor/laravel/framework/src/Illuminate/Database/Connection.php(502): Illuminate\\Database\\Connection->run()
#2 /www/wwwroot/xxx.com/vendor/laravel/framework/src/Illuminate/Database/Connection.php(454): Illuminate\\Database\\Connection->statement()
#3 /www/wwwroot/xxx.com/vendor/laravel/framework/src/Illuminate/Database/Query/Processors/Processor.php(32): Illuminate\\Database\\Connection->insert()
#4 /www/wwwroot/xxx.com/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(3028): Illuminate\\Database\\Query\\Processors\\Processor->processInsertGetId()
#5 /www/wwwroot/xxx.com/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(1657): Illuminate\\Database\\Query\\Builder->insertGetId()
#6 /www/wwwroot/xxx.com/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1188): Illuminate\\Database\\Eloquent\\Builder->__call()
#7 /www/wwwroot/xxx.com/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1153): Illuminate\\Database\\Eloquent\\Model->insertAndSetId()
#8 /www/wwwroot/xxx.com/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(994): Illuminate\\Database\\Eloquent\\Model->performInsert()
#9 /www/wwwroot/xxx.com/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(896): Illuminate\\Database\\Eloquent\\Model->save()
#10 /www/wwwroot/xxx.com/vendor/laravel/framework/src/Illuminate/Support/helpers.php(263): Illuminate\\Database\\Eloquent\\Builder->Illuminate\\Database\\Eloquent\\{closure}()
#11 /www/wwwroot/xxx.com/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(897): tap()
#12 /www/wwwroot/xxx.com/vendor/laravel/framework/src/Illuminate/Support/Traits/ForwardsCalls.php(23): Illuminate\\Database\\Eloquent\\Builder->create()
#13 /www/wwwroot/xxx.com/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(2132): Illuminate\\Database\\Eloquent\\Model->forwardCallTo()
#14 /www/wwwroot/xxx.com/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(2144): Illuminate\\Database\\Eloquent\\Model->__call()
#15 /www/wwwroot/xxx.com/app/Jobs/StatServerJob.php(72): Illuminate\\Database\\Eloquent\\Model::__callStatic()
#16 /www/wwwroot/xxx.com/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): App\\Jobs\\StatServerJob->handle()
#17 /www/wwwroot/xxx.com/vendor/laravel/framework/src/Illuminate/Container/Util.php(40): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#18 /www/wwwroot/xxx.com/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#19 /www/wwwroot/xxx.com/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod()
#20 /www/wwwroot/xxx.com/vendor/laravel/framework/src/Illuminate/Container/Container.php(653): Illuminate\\Container\\BoundMethod::call()
#21 /www/wwwroot/xxx.com/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(128): Illuminate\\Container\\Container->call()
#22 /www/wwwroot/xxx.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Bus\\Dispatcher->Illuminate\\Bus\\{closure}()
#23 /www/wwwroot/xxx.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#24 /www/wwwroot/xxx.com/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(132): Illuminate\\Pipeline\\Pipeline->then()
#25 /www/wwwroot/xxx.com/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(120): Illuminate\\Bus\\Dispatcher->dispatchNow()
#26 /www/wwwroot/xxx.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Queue\\CallQueuedHandler->Illuminate\\Queue\\{closure}()
#27 /www/wwwroot/xxx.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#28 /www/wwwroot/xxx.com/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(122): Illuminate\\Pipeline\\Pipeline->then()
#29 /www/wwwroot/xxx.com/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(70): Illuminate\\Queue\\CallQueuedHandler->dispatchThroughMiddleware()
#30 /www/wwwroot/xxx.com/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(98): Illuminate\\Queue\\CallQueuedHandler->call()
#31 /www/wwwroot/xxx.com/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(428): Illuminate\\Queue\\Jobs\\Job->fire()
#32 /www/wwwroot/xxx.com/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(378): Illuminate\\Queue\\Worker->process()
#33 /www/wwwroot/xxx.com/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(172): Illuminate\\Queue\\Worker->runJob()
#34 /www/wwwroot/xxx.com/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(117): Illuminate\\Queue\\Worker->daemon()
#35 /www/wwwroot/xxx.com/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(101): Illuminate\\Queue\\Console\\WorkCommand->runWorker()
#36 /www/wwwroot/xxx.com/vendor/laravel/horizon/src/Console/WorkCommand.php(51): Illuminate\\Queue\\Console\\WorkCommand->handle()
#37 /www/wwwroot/xxx.com/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Laravel\\Horizon\\Console\\WorkCommand->handle()
#38 /www/wwwroot/xxx.com/vendor/laravel/framework/src/Illuminate/Container/Util.php(40): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#39 /www/wwwroot/xxx.com/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#40 /www/wwwroot/xxx.com/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod()
#41 /www/wwwroot/xxx.com/vendor/laravel/framework/src/Illuminate/Container/Container.php(653): Illuminate\\Container\\BoundMethod::call()
#42 /www/wwwroot/xxx.com/vendor/laravel/framework/src/Illuminate/Console/Command.php(136): Illuminate\\Container\\Container->call()
#43 /www/wwwroot/xxx.com/vendor/symfony/console/Command/Command.php(298): Illuminate\\Console\\Command->execute()
#44 /www/wwwroot/xxx.com/vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\\Component\\Console\\Command\\Command->run()
#45 /www/wwwroot/xxx.com/vendor/symfony/console/Application.php(1040): Illuminate\\Console\\Command->run()
#46 /www/wwwroot/xxx.com/vendor/symfony/console/Application.php(301): Symfony\\Component\\Console\\Application->doRunCommand()
#47 /www/wwwroot/xxx.com/vendor/symfony/console/Application.php(171): Symfony\\Component\\Console\\Application->doRun()
#48 /www/wwwroot/xxx.com/vendor/laravel/framework/src/Illuminate/Console/Application.php(94): Symfony\\Component\\Console\\Application->run()
#49 /www/wwwroot/xxx.com/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(129): Illuminate\\Console\\Application->run()
#50 /www/wwwroot/xxx.com/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle()
#51 {main}

[previous exception] [object] (PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '117-vmess-1678636800' for key 'server_id_server_type_record_at' at /www/wwwroot/xxx.com/vendor/laravel/framework/src/Illuminate/Database/Connection.php:501)
[stacktrace]

**Comment by lajichang0** [comment]
哪位大佬指点下小弟

**Comment by auedu0** [comment]
一样的问题

**Comment by vdt19840** [comment]
好像有一样的问题，但我是多点几次确认就能修改节点排序，额，好几次…

**Comment by lajichang0** [comment]
问了一下chatgpt，提示如下：

这段错误日志显示了一个SQL插入操作失败，并引发了一个完整性约束违规异常。具体来说，该插入操作试图将数据插入到名为v2_stat_server的表中，但是该表上的一个名为server_id_server_type_record_at的唯一约束条件被违反了，因为已经存在一个与该约束条件匹配的记录。

更具体地说，该唯一约束条件要求server_id、server_type和record_at这三个字段的组合必须唯一。然而，插入语句中提供的这些字段的值（即191、vmess和1678377600）已经存在于表中的另一行中，因此插入操作失败并引发了完整性约束违规异常。

要解决这个问题，您需要检查数据库中的表和数据，以确定为什么已经存在具有相同值的行，并决定是否需要对其进行更新或删除，或者是采取其他措施来防止重复插入数据。

**Comment by zou0214** [comment]
将节点的父节点关掉就可以正常排序了

**Comment by jwstaceyOvO** [comment]
+10086
