### ISSUE TITLE
[BUG] pm2任务进程无法完成，购买后一直处于开通中，用户流量数据不同步

### ISSUE THREAD

**Issue by doney0318** [v2board/v2board#794]
🙇‍♂️🙇‍♂️🙇‍♂️注意：XrayR等非V2Board问题请前往项目方提问
🙇‍♂️🙇‍♂️🙇‍♂️Note: XrayR and other non-V2Board issues please go to the project side to ask questions

The V2Board version number you are using
当前使用的V2Board版本号
--------
1.6.0

Briefly describe the problem you are experiencing
简单描述你遇到的问题
--------
用户流量数据不同步，购买节点后一直显示开通中

Screenshot of the reported error(Please do desensitization)
报告错误的截图（请做脱敏处理）
--------
![image](https://user-images.githubusercontent.com/3262032/233234919-e47fa4c3-8bf1-4328-a6f8-8dd7f0471ec5.png)

The latest log files in the storage/logs directory report from #1 (Please do desensitization)
storage/logs 目录下最新的日志文件从 #1 开始报告（请做脱敏处理）
--------
[2023-04-20 09:28:32] local.ERROR: Call to undefined function Laravel\Horizon\posix_getppid() {"exception":"[object] (Error(code: 0): Call to undefined function Laravel\\Horizon\\posix_getppid() at /var/www/v2board/vendor/laravel/horizon/src/Supervisor.php:319)
[stacktrace]
#0 /var/www/v2board/vendor/laravel/horizon/src/Supervisor.php(286): Laravel\\Horizon\\Supervisor->ensureParentIsRunning()
#1 /var/www/v2board/vendor/laravel/horizon/src/Supervisor.php(260): Laravel\\Horizon\\Supervisor->loop()
#2 /var/www/v2board/vendor/laravel/horizon/src/Console/SupervisorCommand.php(100): Laravel\\Horizon\\Supervisor->monitor()
#3 /var/www/v2board/vendor/laravel/horizon/src/Console/SupervisorCommand.php(75): Laravel\\Horizon\\Console\\SupervisorCommand->start()
#4 /var/www/v2board/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Laravel\\Horizon\\Console\\SupervisorCommand->handle()
#5 /var/www/v2board/vendor/laravel/framework/src/Illuminate/Container/Util.php(40): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#6 /var/www/v2board/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#7 /var/www/v2board/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod()
#8 /var/www/v2board/vendor/laravel/framework/src/Illuminate/Container/Container.php(653): Illuminate\\Container\\BoundMethod::call()
#9 /var/www/v2board/vendor/laravel/framework/src/Illuminate/Console/Command.php(136): Illuminate\\Container\\Container->call()
#10 /var/www/v2board/vendor/symfony/console/Command/Command.php(298): Illuminate\\Console\\Command->execute()
#11 /var/www/v2board/vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\\Component\\Console\\Command\\Command->run()
#12 /var/www/v2board/vendor/symfony/console/Application.php(1024): Illuminate\\Console\\Command->run()
#13 /var/www/v2board/vendor/symfony/console/Application.php(299): Symfony\\Component\\Console\\Application->doRunCommand()
#14 /var/www/v2board/vendor/symfony/console/Application.php(171): Symfony\\Component\\Console\\Application->doRun()
#15 /var/www/v2board/vendor/laravel/framework/src/Illuminate/Console/Application.php(94): Symfony\\Component\\Console\\Application->run()
#16 /var/www/v2board/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(129): Illuminate\\Console\\Application->run()
#17 /var/www/v2board/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle()
#18 {main}
"}

**Comment by doney0318** [comment]
php74-php-process 组件没安装，已解决
