### ISSUE TITLE
[BUG]后台新建Hysteria节点报错

### ISSUE THREAD

**Issue by cyril-cheng** [v2board/v2board#806]
🙇‍♂️🙇‍♂️🙇‍♂️注意：XrayR等非V2Board问题请前往项目方提问
🙇‍♂️🙇‍♂️🙇‍♂️Note: XrayR and other non-V2Board issues please go to the project side to ask questions

The V2Board version number you are using
当前使用的V2Board版本号
--------
dev1.7.4

Briefly describe the problem you are experiencing
简单描述你遇到的问题
--------
后台新建Hysteria节点报错

Screenshot of the reported error(Please do desensitization)
报告错误的截图（请做脱敏处理）
--------
请求失败
validation.required

Screenshot of the reported error(Please do desensitization)
报告错误的截图（请做脱敏处理）
--------

The latest log files in the storage/logs directory report from #1 (Please do desensitization)
storage/logs 目录下最新的日志文件从 #1 开始报告（请做脱敏处理）
--------
[previous exception] [object] (PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '2-vmess-1682870400' for key 'v2_stat_server.server_id_server_type_record_at' at /www/wwwroot/v2board/vendor/laravel/framework/src/Illuminate/Database/Connection.php:501)
[stacktrace]
#0 /www/wwwroot/v2board/vendor/laravel/framework/src/Illuminate/Database/Connection.php(501): PDOStatement->execute()
#1 /www/wwwroot/v2board/vendor/laravel/framework/src/Illuminate/Database/Connection.php(705): Illuminate\\Database\\Connection->Illuminate\\Database\\{closure}()
#2 /www/wwwroot/v2board/vendor/laravel/framework/src/Illuminate/Database/Connection.php(672): Illuminate\\Database\\Connection->runQueryCallback()
#3 /www/wwwroot/v2board/vendor/laravel/framework/src/Illuminate/Database/Connection.php(502): Illuminate\\Database\\Connection->run()
#4 /www/wwwroot/v2board/vendor/laravel/framework/src/Illuminate/Database/Connection.php(454): Illuminate\\Database\\Connection->statement()
#5 /www/wwwroot/v2board/vendor/laravel/framework/src/Illuminate/Database/Query/Processors/Processor.php(32): Illuminate\\Database\\Connection->insert()
#6 /www/wwwroot/v2board/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(3028): Illuminate\\Database\\Query\\Processors\\Processor->processInsertGetId()
#7 /www/wwwroot/v2board/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(1657): Illuminate\\Database\\Query\\Builder->insertGetId()
#8 /www/wwwroot/v2board/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1188): Illuminate\\Database\\Eloquent\\Builder->__call()
#9 /www/wwwroot/v2board/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1153): Illuminate\\Database\\Eloquent\\Model->insertAndSetId()
#10 /www/wwwroot/v2board/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(994): Illuminate\\Database\\Eloquent\\Model->performInsert()
#11 /www/wwwroot/v2board/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(896): Illuminate\\Database\\Eloquent\\Model->save()
#12 /www/wwwroot/v2board/vendor/laravel/framework/src/Illuminate/Support/helpers.php(263): Illuminate\\Database\\Eloquent\\Builder->Illuminate\\Database\\Eloquent\\{closure}()
#13 /www/wwwroot/v2board/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(897): tap()
#14 /www/wwwroot/v2board/vendor/laravel/framework/src/Illuminate/Support/Traits/ForwardsCalls.php(23): Illuminate\\Database\\Eloquent\\Builder->create()
#15 /www/wwwroot/v2board/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(2132): Illuminate\\Database\\Eloquent\\Model->forwardCallTo()
#16 /www/wwwroot/v2board/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(2144): Illuminate\\Database\\Eloquent\\Model->__call()
#17 /www/wwwroot/v2board/app/Jobs/StatServerJob.php(64): Illuminate\\Database\\Eloquent\\Model::__callStatic()
#18 /www/wwwroot/v2board/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): App\\Jobs\\StatServerJob->handle()
#19 /www/wwwroot/v2board/vendor/laravel/framework/src/Illuminate/Container/Util.php(40): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#20 /www/wwwroot/v2board/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#21 /www/wwwroot/v2board/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod()
#22 /www/wwwroot/v2board/vendor/laravel/framework/src/Illuminate/Container/Container.php(653): Illuminate\\Container\\BoundMethod::call()
#23 /www/wwwroot/v2board/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(128): Illuminate\\Container\\Container->call()
#24 /www/wwwroot/v2board/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Bus\\Dispatcher->Illuminate\\Bus\\{closure}()
#25 /www/wwwroot/v2board/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#26 /www/wwwroot/v2board/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(132): Illuminate\\Pipeline\\Pipeline->then()
#27 /www/wwwroot/v2board/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(120): Illuminate\\Bus\\Dispatcher->dispatchNow()
#28 /www/wwwroot/v2board/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Queue\\CallQueuedHandler->Illuminate\\Queue\\{closure}()
#29 /www/wwwroot/v2board/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#30 /www/wwwroot/v2board/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(122): Illuminate\\Pipeline\\Pipeline->then()
#31 /www/wwwroot/v2board/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(70): Illuminate\\Queue\\CallQueuedHandler->dispatchThroughMiddleware()
#32 /www/wwwroot/v2board/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(98): Illuminate\\Queue\\CallQueuedHandler->call()
#33 /www/wwwroot/v2board/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(428): Illuminate\\Queue\\Jobs\\Job->fire()
#34 /www/wwwroot/v2board/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(378): Illuminate\\Queue\\Worker->process()
#35 /www/wwwroot/v2board/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(172): Illuminate\\Queue\\Worker->runJob()
#36 /www/wwwroot/v2board/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(117): Illuminate\\Queue\\Worker->daemon()
#37 /www/wwwroot/v2board/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(101): Illuminate\\Queue\\Console\\WorkCommand->runWorker()
#38 /www/wwwroot/v2board/vendor/laravel/horizon/src/Console/WorkCommand.php(51): Illuminate\\Queue\\Console\\WorkCommand->handle()
#39 /www/wwwroot/v2board/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Laravel\\Horizon\\Console\\WorkCommand->handle()
#40 /www/wwwroot/v2board/vendor/laravel/framework/src/Illuminate/Container/Util.php(40): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#41 /www/wwwroot/v2board/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#42 /www/wwwroot/v2board/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod()
#43 /www/wwwroot/v2board/vendor/laravel/framework/src/Illuminate/Container/Container.php(653): Illuminate\\Container\\BoundMethod::call()
#44 /www/wwwroot/v2board/vendor/laravel/framework/src/Illuminate/Console/Command.php(136): Illuminate\\Container\\Container->call()
#45 /www/wwwroot/v2board/vendor/symfony/console/Command/Command.php(298): Illuminate\\Console\\Command->execute()
#46 /www/wwwroot/v2board/vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\\Component\\Console\\Command\\Command->run()
#47 /www/wwwroot/v2board/vendor/symfony/console/Application.php(1040): Illuminate\\Console\\Command->run()
#48 /www/wwwroot/v2board/vendor/symfony/console/Application.php(301): Symfony\\Component\\Console\\Application->doRunCommand()
#49 /www/wwwroot/v2board/vendor/symfony/console/Application.php(171): Symfony\\Component\\Console\\Application->doRun()
#50 /www/wwwroot/v2board/vendor/laravel/framework/src/Illuminate/Console/Application.php(94): Symfony\\Component\\Console\\Application->run()
#51 /www/wwwroot/v2board/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(129): Illuminate\\Console\\Application->run()
#52 /www/wwwroot/v2board/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle()
#53 {main}
"}

**Comment by tokumeikoi** [comment]
dev中已经处理

**Comment by YinPengZi** [comment]
我在正式版中也出现了这样的问题

**Comment by YinPengZi** [comment]
[2023-06-05 00:10:03] local.ERROR: SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'title' at row 1 (SQL: insert into `v2_log` (`title`, `level`, `host`, `uri`, `method`, `ip`, `data`, `context`, `created_at`, `updated_at`) values (SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '1.00-591-1685808000' for key 'server_rate_user_id_record_at' (SQL: insert into `v2_stat_user` (`user_id`, `u`, `d`, `server_rate`, `created_at`, `updated_at`, `record_type`, `record_at`) values (591, 23624808, 3162597664, 1, 1685895003, 1685895003, d, 1685808000)), ERROR, http://localhost, /, GET, 127.0.0.1, [], {"exception":{"\u0000*\u0000sql":"insert into `v2_stat_user` (`user_id`, `u`, `d`, `server_rate`, `created_at`, `updated_at`, `record_type`, `record_at`) values (?, ?, ?, ?, ?, ?, ?, ?)","\u0000*\u0000bindings":[591,23624808,3162597664,1,1685895003,1685895003,"d",1685808000],"\u0000*\u0000message":"SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '1.00-591-1685808000' for key 'server_rate_user_id_record_at' (SQL: insert into `v2_stat_user` (`user_id`, `u`, `d`, `server_rate`, `created_at`, `updated_at`, `record_type`, `record_at`) values (591, 23624808, 3162597664, 1, 1685895003, 1685895003, d, 1685808000))","\u0000Exception\u0000string":"","\u0000*\u0000code":"23000","\u0000*\u0000file":"\/www\/wwwroot\/v2board\/vendor\/laravel\/framework\/src\/Illuminate\/Database\/Connection.php","\u0000*\u0000line":712,"\u0000Exception\u0000trace":[{"file":"\/www\/wwwroot\/v2board\/vendor\/laravel\/framework\/src\/Illuminate\/Database\/Connection.php","line":672,"function":"runQueryCallback","class":"Illuminate\\Database\\Connection","type":"->"},{"file":"\/www\/wwwroot\/v2board\/vendor\/laravel\/framework\/src\/Illuminate\/Database\/Connection.php","line":502,"function":"run","class":"Illuminate\\Database\\Connection","type":"->"},{"file":"\/www\/wwwroot\/v2board\/vendor\/laravel\/framework\/src\/Illuminate\/Database\/Connection.php","line":454,"function":"statement","class":"Illuminate\\Database\\Connection","type":"->"},{"file":"\/www\/wwwroot\/v2board\/vendor\/laravel\/framework\/src\/Illuminate\/Database\/Query\/Builder.php","line":2980,"function":"insert","class":"Illuminate\\Database\\Connection","type":"->"},{"file":"\/www\/wwwroot\/v2board\/vendor\/laravel\/framework\/src\/Illuminate\/Database\/Eloquent\/Builder.php","line":1657,"function":"insert","class":"Illuminate\\Database\\Query\\Builder","type":"->"},{"file":"\/www\/wwwroot\/v2board\/vendor\/laravel\/framework\/src\/Illuminate\/Support\/Traits\/ForwardsCalls.php","line":23,"function":"__call","class":"Illuminate\\Database\\Eloquent\\Builder","type":"->"},{"file":"\/www\/wwwroot\/v2board\/vendor\/laravel\/framework\/src\/Illuminate\/Database\/Eloquent\/Model.php","line":2132,"function":"forwardCallTo","class":"Illuminate\\Database\\Eloquent\\Model","type":"->"},{"file":"\/www\/wwwroot\/v2board\/vendor\/laravel\/framework\/src\/Illuminate\/Database\/Eloquent\/Model.php","line":2144,"function":"__call","class":"Illuminate\\Database\\Eloquent\\Model","type":"->"},{"file":"\/www\/wwwroot\/v2board\/app\/Console\/Commands\/V2boardStatistics.php","line":102,"function":"__callStatic","class":"Illuminate\\Database\\Eloquent\\Model","type":"::"},{"file":"\/www\/wwwroot\/v2board\/app\/Console\/Commands\/V2boardStatistics.php","line":50,"function":"statUser","class":"App\\Console\\Commands\\V2boardStatistics","type":"->"},{"file":"\/www\/wwwroot\/v2board\/vendor\/laravel\/framework\/src\/Illuminate\/Container\/BoundMethod.php","line":36,"function":"handle","class":"App\\Console\\Commands\\V2boardStatistics","type":"->"},{"file":"\/www\/wwwroot\/v2board\/vendor\/laravel\/framework\/src\/Illuminate\/Container\/Util.php","line":40,"function":"Illuminate\\Container\\{closure}","class":"Illuminate\\Container\\BoundMethod","type":"::"},{"file":"\/www\/wwwroot\/v2board\/vendor\/laravel\/framework\/src\/Illuminate\/Container\/BoundMethod.php","line":93,"function":"unwrapIfClosure","class":"Illuminate\\Container\\Util","type":"::"},{"file":"\/www\/wwwroot\/v2board\/vendor\/laravel\/framework\/src\/Illuminate\/Container\/BoundMethod.php","line":37,"function":"callBoundMethod","class":"Illuminate\\Container\\BoundMethod","type":"::"},{"file":"\/www\/wwwroot\/v2board\/vendor\/laravel\/framework\/src\/Illuminate\/Container\/Container.php","line":653,"function":"call","class":"Illuminate\\Container\\BoundMethod","type":"::"},{"file":"\/www\/wwwroot\/v2board\/vendor\/laravel\/framework\/src\/Illuminate\/Console\/Command.php","line":136,"function":"call","class":"Illuminate\\Container\\Container","type":"->"},{"file":"\/www\/wwwroot\/v2board\/vendor\/symfony\/console\/Command\/Command.php","line":298,"function":"execute","class":"Illuminate\\Console\\Command","type":"->"},{"file":"\/www\/wwwroot\/v2board\/vendor\/laravel\/framework\/src\/Illuminate\/Console\/Command.php","line":121,"function":"run","class":"Symfony\\Component\\Console\\Command\\Command","type":"->"},{"file":"\/www\/wwwroot\/v2board\/vendor\/symfony\/console\/Application.php","line":1040,"function":"run","class":"Illuminate\\Console\\Command","type":"->"},{"file":"\/www\/wwwroot\/v2board\/vendor\/symfony\/console\/Application.php","line":301,"function":"doRunCommand","class":"Symfony\\Component\\Console\\Application","type":"->"},{"file":"\/www\/wwwroot\/v2board\/vendor\/symfony\/console\/Application.php","line":171,"function":"doRun","class":"Symfony\\Component\\Console\\Application","type":"->"},{"file":"\/www\/wwwroot\/v2board\/vendor\/laravel\/framework\/src\/Illuminate\/Console\/Application.php","line":94,"function":"run","class":"Symfony\\Component\\Console\\Application","type":"->"},{"file":"\/www\/wwwroot\/v2board\/vendor\/laravel\/framework\/src\/Illuminate\/Foundation\/Console\/Kernel.php","line":129,"function":"run","class":"Illuminate\\Console\\Application","type":"->"},{"file":"\/www\/wwwroot\/v2board\/artisan","line":37,"function":"handle","class":"Illuminate\\Foundation\\Console\\Kernel","type":"->"}],"\u0000Exception\u0000previous":{"errorInfo":["23000",1062,"Duplicate entry '1.00-591-1685808000' for key 'server_rate_user_id_record_at'"]},"errorInfo":["23000",1062,"Duplicate entry '1.00-591-1685808000' for key 'server_rate_user_id_record_at'"]}}, 1685895003, 1685895003))/www/wwwroot/v2board/vendor/laravel/framework/src/Illuminate/Database/Connection.php#0 /www/wwwroot/v2board/vendor/laravel/framework/src/Illuminate/Database/Connection.php(672): Illuminate\Database\Connection->runQueryCallback()
#1 /www/wwwroot/v2board/vendor/laravel/framework/src/Illuminate/Database/Connection.php(502): Illuminate\Database\Connection->run()
#2 /www/wwwroot/v2board/vendor/laravel/framework/src/Illuminate/Database/Connection.php(454): Illuminate\Database\Connection->statement()
#3 /www/wwwroot/v2board/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2980): Illuminate\Database\Connection->insert()
#4 /www/wwwroot/v2board/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(1657): Illuminate\Database\Query\Builder->insert()
#5 /www/wwwroot/v2board/vendor/laravel/framework/src/Illuminate/Support/Traits/ForwardsCalls.php(23): Illuminate\Database\Eloquent\Builder->__call()
#6 /www/wwwroot/v2board/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(2132): Illuminate\Database\Eloquent\Model->forwardCallTo()
#7 /www/wwwroot/v2board/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(2144): Illuminate\Database\Eloquent\Model->__call()
#8 /www/wwwroot/v2board/app/Logging/MysqlLoggerHandler.php(38): Illuminate\Database\Eloquent\Model::__callStatic()
#9 /www/wwwroot/v2board/vendor/monolog/monolog/src/Monolog/Handler/AbstractProcessingHandler.php(48): App\Logging\MysqlLoggerHandler->write()
#10 /www/wwwroot/v2board/vendor/monolog/monolog/src/Monolog/Logger.php(399): Monolog\Handler\AbstractProcessingHandler->handle()
#11 /www/wwwroot/v2board/vendor/monolog/monolog/src/Monolog/Logger.php(650): Monolog\Logger->addRecord()
#12 /www/wwwroot/v2board/vendor/laravel/framework/src/Illuminate/Log/Logger.php(183): Monolog\Logger->error()
#13 /www/wwwroot/v2board/vendor/laravel/framework/src/Illuminate/Log/Logger.php(94): Illuminate\Log\Logger->writeLog()
#14 /www/wwwroot/v2board/vendor/laravel/framework/src/Illuminate/Log/LogManager.php(590): Illuminate\Log\Logger->error()
#15 /www/wwwroot/v2board/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(252): Illuminate\Log\LogManager->error()
#16 /www/wwwroot/v2board/app/Exceptions/Handler.php(42): Illuminate\Foundation\Exceptions\Handler->report()
#17 /www/wwwroot/v2board/vendor/nunomaduro/collision/src/Adapters/Laravel/ExceptionHandler.php(57): App\Exceptions\Handler->report()
#18 /www/wwwroot/v2board/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(366): NunoMaduro\Collision\Adapters\Laravel\ExceptionHandler->report()
#19 /www/wwwroot/v2board/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(131): Illuminate\Foundation\Console\Kernel->reportException()
#20 /www/wwwroot/v2board/artisan(37): Illuminate\Foundation\Console\Kernel->handle()
#21 {main}  



这是最新的日志
