### ISSUE TITLE
[BUG]管理页面服务器配置的三个部分加载异常

### ISSUE THREAD

**Issue by yxdesu** [v2board/v2board#879]
🙇‍♂️🙇‍♂️🙇‍♂️注意：XrayR等非V2Board问题请前往项目方提问
🙇‍♂️🙇‍♂️🙇‍♂️Note: XrayR and other non-V2Board issues please go to the project side to ask questions

The V2Board version number you are using
当前使用的V2Board版本号
--------
1.7.4

Briefly describe the problem you are experiencing
简单描述你遇到的问题
--------
后台管理界面服务器配置的三个部分，节点、权限、路由管理均加载异常无法使用，其他部分功能无影响。

Screenshot of the reported error(Please do desensitization)
报告错误的截图（请做脱敏处理）
--------
![image](https://github.com/v2board/v2board/assets/135617165/f42cae86-234e-4ee7-8ce0-6f86325b164b)

Screenshot of the reported error(Please do desensitization)
报告错误的截图（请做脱敏处理）
--------

The latest log files in the storage/logs directory report from #1 (Please do desensitization)
storage/logs 目录下最新的日志文件从 #1 开始报告（请做脱敏处理）
--------
[2023-06-19 02:55:18] local.ERROR: SQLSTATE[HY000] [2002] No such file or directory (SQL: insert into `v2_log` (`title`, `level`, `host`, `uri`, `method`, `ip`, `data`, `context`, `created_at`, `updated_at`) values (SQLSTATE[HY000] [2002] No such file or directory (SQL: select * from `v2_server_vmess` where `v2_server_vmess`.`id` = 1 limit 1), ERROR, https://域名, /api/v1/server/UniProxy/config?node_id=1&node_type=v2ray&token=FLY3746%23%24YhABjJcsz, GET, IP, {"node_id":"1","node_type":"v2ray","token":"FLY3746#$YhABjJcsz"}, {"exception":{"\u0000*\u0000sql":"select * from `v2_server_vmess` where `v2_server_vmess`.`id` = ? limit 1","\u0000*\u0000bindings":["1"],"\u0000*\u0000message":"SQLSTATE[HY000] [2002] No such file or directory (SQL: select * from `v2_server_vmess` where `v2_server_vmess`.`id` = 1 limit 1)","\u0000Exception\u0000string":"","\u0000*\u0000code":2002,"\u0000*\u0000file":"\/www\/wwwroot\/域名\/vendor\/laravel\/framework\/src\/Illuminate\/Database\/Connection.php","\u0000*\u0000line":712,"\u0000Exception\u0000trace":[{"file":"\/www\/wwwroot\/域名\/vendor\/laravel\/framework\/src\/Illuminate\/Database\/Connection.php","line":672,"function":"runQueryCallback","class":"Illuminate\\Database\\Connection","type":"->"},{"file":"\/www\/wwwroot\/域名\/vendor\/laravel\/framework\/src\/Illuminate\/Database\/Connection.php","line":376,"function":"run","class":"Illuminate\\Database\\Connection","type":"->"},{"file":"\/www\/wwwroot\/域名\/vendor\/laravel\/framework\/src\/Illuminate\/Database\/Query\/Builder.php","line":2414,"function":"select","class":"Illuminate\\Database\\Connection","type":"->"},{"file":"\/www\/wwwroot\/域名\/vendor\/laravel\/framework\/src\/Illuminate\/Database\/Query\/Builder.php","line":2402,"function":"runSelect","class":"Illuminate\\Database\\Query\\Builder","type":"->"},{"file":"\/www\/wwwroot\/域名\/vendor\/laravel\/framework\/src\/Illuminate\/Database\/Query\/Builder.php","line":2936,"function":"Illuminate\\Database\\Query\\{closure}","class":"Illuminate\\Database\\Query\\Builder","type":"->"},{"file":"\/www\/wwwroot\/域名\/vendor\/laravel\/framework\/src\/Illuminate\/Database\/Query\/Builder.php","line":2403,"function":"onceWithColumns","class":"Illuminate\\Database\\Query\\Builder","type":"->"},{"file":"\/www\/wwwroot\/域名\/vendor\/laravel\/framework\/src\/Illuminate\/Database\/Eloquent\/Builder.php","line":625,"function":"get","class":"Illuminate\\Database\\Query\\Builder","type":"->"},{"file":"\/www\/wwwroot\/域名\/vendor\/laravel\/framework\/src\/Illuminate\/Database\/Eloquent\/Builder.php","line":609,"function":"getModels","class":"Illuminate\\Database\\Eloquent\\Builder","type":"->"},{"file":"\/www\/wwwroot\/域名\/vendor\/laravel\/framework\/src\/Illuminate\/Database\/Concerns\/BuildsQueries.php","line":294,"function":"get","class":"Illuminate\\Database\\Eloquent\\Builder","type":"->"},{"file":"\/www\/wwwroot\/域名\/vendor\/laravel\/framework\/src\/Illuminate\/Database\/Eloquent\/Builder.php","line":400,"function":"first","class":"Illuminate\\Database\\Eloquent\\Builder","type":"->"},{"file":"\/www\/wwwroot\/域名\/vendor\/laravel\/framework\/src\/Illuminate\/Support\/Traits\/ForwardsCalls.php","line":23,"function":"find","class":"Illuminate\\Database\\Eloquent\\Builder","type":"->"},{"file":"\/www\/wwwroot\/域名\/vendor\/laravel\/framework\/src\/Illuminate\/Database\/Eloquent\/Model.php","line":2132,"function":"forwardCallTo","class":"Illuminate\\Database\\Eloquent\\Model","type":"->"},{"file":"\/www\/wwwroot\/域名\/vendor\/laravel\/framework\/src\/Illuminate\/Database\/Eloquent\/Model.php","line":2144,"function":"__call","class":"Illuminate\\Database\\Eloquent\\Model","type":"->"},{"file":"\/www\/wwwroot\/域名\/app\/Services\/ServerService.php","line":268,"function":"__callStatic","class":"Illuminate\\Database\\Eloquent\\Model","type":"::"},{"file":"\/www\/wwwroot\/域名\/app\/Http\/Controllers\/Server\/UniProxyController.php","line":37,"function":"getServer","class":"App\\Services\\ServerService","type":"->"},{"function":"__construct","class":"App\\Http\\Controllers\\Server\\UniProxyController","type":"->"},{"file":"\/www\/wwwroot\/域名\/vendor\/laravel\/framework\/src\/Illuminate\/Container\/Container.php","line":917,"function":"newInstanceArgs","class":"ReflectionClass","type":"->"},{"file":"\/www\/wwwroot\/域名\/vendor\/laravel\/framework\/src\/Illuminate\/Container\/Container.php","line":758,"function":"build","class":"Illuminate\\Container\\Container","type":"->"},{"file":"\/www\/wwwroot\/域名\/vendor\/laravel\/framework\/src\/Illuminate\/Foundation\/Application.php","line":851,"function":"resolve","class":"Illuminate\\Container\\Container","type":"->"},{"file":"\/www\/wwwroot\/域名\/vendor\/laravel\/framework\/src\/Illuminate\/Container\/Container.php","line":694,"function":"resolve","class":"Illuminate\\Foundation\\Application","type":"->"},{"file":"\/www\/wwwroot\/域名\/vendor\/laravel\/framework\/src\/Illuminate\/Foundation\/Application.php","line":836,"function":"make","class":"Illuminate\\Container\\Container","type":"->"},{"file":"\/www\/wwwroot\/域名\/vendor\/laravel\/framework\/src\/Illuminate\/Support\/Facades\/Facade.php","line":261,"function":"make","class":"Illuminate\\Foundation\\Application","type":"->"},{"file":"\/www\/wwwroot\/域名\/app\/Http\/Routes\/ServerRoute.php","line":14,"function":"__callStatic","class":"Illuminate\\Support\\Facades\\Facade","type":"::"},{"file":"\/www\/wwwroot\/域名\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/Route.php","line":238,"function":"App\\Http\\Routes\\{closure}","class":"App\\Http\\Routes\\ServerRoute","type":"->"},{"file":"\/www\/wwwroot\/域名\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/Route.php","line":208,"function":"runCallable","class":"Illuminate\\Routing\\Route","type":"->"},{"file":"\/www\/wwwroot\/域名\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/Router.php","line":721,"function":"run","class":"Illuminate\\Routing\\Route","type":"->"},{"file":"\/www\/wwwroot\/域名\/vendor\/laravel\/framework\/src\/Illuminate\/Pipeline\/Pipeline.php","line":128,"function":"Illuminate\\Routing\\{closure}","class":"Illuminate\\Routing\\Router","type":"->"},{"file":"\/www\/wwwroot\/域名\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/Middleware\/SubstituteBindings.php","line":50,"function":"Illuminate\\Pipeline\\{closure}","class":"Illuminate\\Pipeline\\Pipeline","type":"->"},{"file":"\/www\/wwwroot\/域名\/vendor\/laravel\/framework\/src\/Illuminate\/Pipeline\/Pipeline.php","line":167,"function":"handle","class":"Illuminate\\Routing\\Middleware\\SubstituteBindings","type":"->"},{"file":"\/www\/wwwroot\/域名\/app\/Http\/Middleware\/Language.php","line":15,"function":"Illuminate\\Pipeline\\{closure}","class":"Illuminate\\Pipeline\\Pipeline","type":"->"},{"file":"\/www\/wwwroot\/域名\/vendor\/laravel\/framework\/src\/Illuminate\/Pipeline\/Pipeline.php","line":167,"function":"handle","class":"App\\Http\\Middleware\\Language","type":"->"},{"file":"\/www\/wwwroot\/域名\/app\/Http\/Middleware\/ForceJson.php","line":20,"function":"Illuminate\\Pipeline\\{closure}","class":"Illuminate\\Pipeline\\Pipeline","type":"->"},{"file":"\/www\/wwwroot\/域名\/vendor\/laravel\/framework\/src\/Illuminate\/Pipeline\/Pipeline.php","line":167,"function":"handle","class":"App\\Http\\Middleware\\ForceJson","type":"->"},{"file":"\/www\/wwwroot\/域名\/vendor\/laravel\/framework\/src\/Illuminate\/Pipeline\/Pipeline.php","line":103,"function":"Illuminate\\Pipeline\\{closure}","class":"Illuminate\\Pipeline\\Pipeline","type":"->"},{"file":"\/www\/wwwroot\/域名\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/Router.php","line":723,"function":"then","class":"Illuminate\\Pipeline\\Pipeline","type":"->"},{"file":"\/www\/wwwroot\/域名\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/Router.php","line":698,"function":"runRouteWithinStack","class":"Illuminate\\Routing\\Router","type":"->"},{"file":"\/www\/wwwroot\/域名\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/Router.php","line":662,"function":"runRoute","class":"Illuminate\\Routing\\Router","type":"->"},{"file":"\/www\/wwwroot\/域名\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/Router.php","line":651,"function":"dispatchToRoute","class":"Illuminate\\Routing\\Router","type":"->"},{"file":"\/www\/wwwroot\/域名\/vendor\/laravel\/framework\/src\/Illuminate\/Foundation\/Http\/Kernel.php","line":167,"function":"dispatch","class":"Illuminate\\Routing\\Router","type":"->"},{"file":"\/www\/wwwroot\/域名\/vendor\/laravel\/framework\/src\/Illuminate\/Pipeline\/Pipeline.php","line":128,"function":"Illuminate\\Foundation\\Http\\{closure}","class":"Illuminate\\Foundation\\Http\\Kernel","type":"->"},{"file":"\/www\/wwwroot\/域名\/vendor\/laravel\/framework\/src\/Illuminate\/Foundation\/Http\/Middleware\/TransformsRequest.php","line":21,"function":"Illuminate\\Pipeline\\{closure}","class":"Illuminate\\Pipeline\\Pipeline","type":"->"},{"file":"\/www\/wwwroot\/域名\/vendor\/laravel\/framework\/src\/Illuminate\/Foundation\/Http\/Middleware\/ConvertEmptyStringsToNull.php","line":31,"function":"handle","class":"Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest","type":"->"},{"file":"\/www\/wwwroot\/域名\/vendor\/laravel\/framework\/src\/Illuminate\/Pipeline\/Pipeline.php","line":167,"function":"handle","class":"Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull","type":"->"},{"file":"\/www\/wwwroot\/域名\/vendor\/laravel\/framework\/src\/Illuminate\/Foundation\/Http\/Middleware\/TransformsRequest.php","line":21,"function":"Illuminate\\Pipeline\\{closure}","class":"Illuminate\\Pipeline\\Pipeline","type":"->"},{"file":"\/www\/wwwroot\/域名\/vendor\/laravel\/framework\/src\/Illuminate\/Foundation\/Http\/Middleware\/TrimStrings.php","line":40,"function":"handle","class":"Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest","type":"->"},{"file":"\/www\/wwwroot\/域名\/vendor\/laravel\/framework\/src\/Illuminate\/Pipeline\/Pipeline.php","line":167,"function":"handle","class":"Illuminate\\Foundation\\Http\\Middleware\\TrimStrings","type":"->"},{"file":"\/www\/wwwroot\/域名\/vendor\/laravel\/framework\/src\/Illuminate\/Foundation\/Http\/Middleware\/ValidatePostSize.php","line":27,"function":"Illuminate\\Pipeline\\{closure}","class":"Illuminate\\Pipeline\\Pipeline","type":"->"},{"file":"\/www\/wwwroot\/域名\/vendor\/laravel\/framework\/src\/Illuminate\/Pipeline\/Pipeline.php","line":167,"function":"handle","class":"Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize","type":"->"},{"file":"\/www\/wwwroot\/域名\/vendor\/laravel\/framework\/src\/Illuminate\/Foundation\/Http\/Middleware\/PreventRequestsDuringMaintenance.php","line":86,"function":"Illuminate\\Pipeline\\{closure}","class":"Illuminate\\Pipeline\\Pipeline","type":"->"},{"file":"\/www\/wwwroot\/域名\/vendor\/laravel\/framework\/src\/Illuminate\/Pipeline\/Pipeline.php","line":167,"function":"handle","class":"Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance","type":"->"},{"file":"\/www\/wwwroot\/域名\/vendor\/fideloper\/proxy\/src\/TrustProxies.php","line":57,"function":"Illuminate\\Pipeline\\{closure}","class":"Illuminate\\Pipeline\\Pipeline","type":"->"},{"file":"\/www\/wwwroot\/域名\/vendor\/laravel\/framework\/src\/Illuminate\/Pipeline\/Pipeline.php","line":167,"function":"handle","class":"Fideloper\\Proxy\\TrustProxies","type":"->"},{"file":"\/www\/wwwroot\/域名\/app\/Http\/Middleware\/CORS.php","line":18,"function":"Illuminate\\Pipeline\\{closure}","class":"Illuminate\\Pipeline\\Pipeline","type":"->"},{"file":"\/www\/wwwroot\/域名\/vendor\/laravel\/framework\/src\/Illuminate\/Pipeline\/Pipeline.php","line":167,"function":"handle","class":"App\\Http\\Middleware\\CORS","type":"->"},{"file":"\/www\/wwwroot\/域名\/vendor\/laravel\/framework\/src\/Illuminate\/Pipeline\/Pipeline.php","line":103,"function":"Illuminate\\Pipeline\\{closure}","class":"Illuminate\\Pipeline\\Pipeline","type":"->"},{"file":"\/www\/wwwroot\/域名\/vendor\/laravel\/framework\/src\/Illuminate\/Foundation\/Http\/Kernel.php","line":142,"function":"then","class":"Illuminate\\Pipeline\\Pipeline","type":"->"},{"file":"\/www\/wwwroot\/域名\/vendor\/laravel\/framework\/src\/Illuminate\/Foundation\/Http\/Kernel.php","line":111,"function":"sendRequestThroughRouter","class":"Illuminate\\Foundation\\Http\\Kernel","type":"->"},{"file":"\/www\/wwwroot\/域名\/public\/index.php","line":55,"function":"handle","class":"Illuminate\\Foundation\\Http\\Kernel","type":"->"}],"\u0000Exception\u0000previous":{"errorInfo":["HY000",2002,"No such file or directory"]},"errorInfo":["HY000",2002,"No such file or directory"]}}, 1687114518, 1687114518))/www/wwwroot/域名/vendor/laravel/framework/src/Illuminate/Database/Connection.php#0 /www/wwwroot/域名/vendor/laravel/framework/src/Illuminate/Database/Connection.php(672): Illuminate\Database\Connection->runQueryCallback()
#1 /www/wwwroot/域名/vendor/laravel/framework/src/Illuminate/Database/Connection.php(502): Illuminate\Database\Connection->run()
#2 /www/wwwroot/域名/vendor/laravel/framework/src/Illuminate/Database/Connection.php(454): Illuminate\Database\Connection->statement()
#3 /www/wwwroot/域名/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2980): Illuminate\Database\Connection->insert()
#4 /www/wwwroot/域名/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(1657): Illuminate\Database\Query\Builder->insert()
#5 /www/wwwroot/域名/vendor/laravel/framework/src/Illuminate/Support/Traits/ForwardsCalls.php(23): Illuminate\Database\Eloquent\Builder->__call()
#6 /www/wwwroot/域名/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(2132): Illuminate\Database\Eloquent\Model->forwardCallTo()
#7 /www/wwwroot/域名/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(2144): Illuminate\Database\Eloquent\Model->__call()
#8 /www/wwwroot/域名/app/Logging/MysqlLoggerHandler.php(38): Illuminate\Database\Eloquent\Model::__callStatic()
#9 /www/wwwroot/域名/vendor/monolog/monolog/src/Monolog/Handler/AbstractProcessingHandler.php(48): App\Logging\MysqlLoggerHandler->write()
#10 /www/wwwroot/域名/vendor/monolog/monolog/src/Monolog/Logger.php(399): Monolog\Handler\AbstractProcessingHandler->handle()
#11 /www/wwwroot/域名/vendor/monolog/monolog/src/Monolog/Logger.php(650): Monolog\Logger->addRecord()
#12 /www/wwwroot/域名/vendor/laravel/framework/src/Illuminate/Log/Logger.php(183): Monolog\Logger->error()
#13 /www/wwwroot/域名/vendor/laravel/framework/src/Illuminate/Log/Logger.php(94): Illuminate\Log\Logger->writeLog()
#14 /www/wwwroot/域名/vendor/laravel/framework/src/Illuminate/Log/LogManager.php(590): Illuminate\Log\Logger->error()
#15 /www/wwwroot/域名/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(252): Illuminate\Log\LogManager->error()
#16 /www/wwwroot/域名/app/Exceptions/Handler.php(42): Illuminate\Foundation\Exceptions\Handler->report()
#17 /www/wwwroot/域名/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(49): App\Exceptions\Handler->report()
#18 /www/wwwroot/域名/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Illuminate\Routing\Pipeline->handleException()
#19 /www/wwwroot/域名/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(50): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#20 /www/wwwroot/域名/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Routing\Middleware\SubstituteBindings->handle()
#21 /www/wwwroot/域名/app/Http/Middleware/Language.php(15): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#22 /www/wwwroot/域名/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): App\Http\Middleware\Language->handle()
#23 /www/wwwroot/域名/app/Http/Middleware/ForceJson.php(20): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#24 /www/wwwroot/域名/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): App\Http\Middleware\ForceJson->handle()
#25 /www/wwwroot/域名/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#26 /www/wwwroot/域名/vendor/laravel/framework/src/Illuminate/Routing/Router.php(723): Illuminate\Pipeline\Pipeline->then()
#27 /www/wwwroot/域名/vendor/laravel/framework/src/Illuminate/Routing/Router.php(698): Illuminate\Routing\Router->runRouteWithinStack()
#28 /www/wwwroot/域名/vendor/laravel/framework/src/Illuminate/Routing/Router.php(662): Illuminate\Routing\Router->runRoute()
#29 /www/wwwroot/域名/vendor/laravel/framework/src/Illuminate/Routing/Router.php(651): Illuminate\Routing\Router->dispatchToRoute()
#30 /www/wwwroot/域名/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(167): Illuminate\Routing\Router->dispatch()
#31 /www/wwwroot/域名/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}()
#32 /www/wwwroot/域名/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#33 /www/wwwroot/域名/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle()
#34 /www/wwwroot/域名/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Foundation\Http\Middleware\ConvertEmptyStringsToNull->handle()
#35 /www/wwwroot/域名/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#36 /www/wwwroot/域名/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle()
#37 /www/wwwroot/域名/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Foundation\Http\Middleware\TrimStrings->handle()
#38 /www/wwwroot/域名/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#39 /www/wwwroot/域名/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Foundation\Http\Middleware\ValidatePostSize->handle()
#40 /www/wwwroot/域名/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#41 /www/wwwroot/域名/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Foundation\Http\Middleware\PreventRequestsDuringMaintenance->handle()
#42 /www/wwwroot/域名/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#43 /www/wwwroot/域名/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fideloper\Proxy\TrustProxies->handle()
#44 /www/wwwroot/域名/app/Http/Middleware/CORS.php(18): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#45 /www/wwwroot/域名/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): App\Http\Middleware\CORS->handle()
#46 /www/wwwroot/域名/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#47 /www/wwwroot/域名/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(142): Illuminate\Pipeline\Pipeline->then()
#48 /www/wwwroot/域名/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(111): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter()
#49 /www/wwwroot/域名/public/index.php(55): Illuminate\Foundation\Http\Kernel->handle()
#50 {main}

**Comment by EdNovas** [comment]
升级后我也遇到了该问题，重装了下面板解决的。

**Comment by yxdesu** [comment]
> 升级后我也遇到了该问题，重装了下面板解决的。

是的，我也是，重装解决
